### PR TITLE
AVRO-2175: Import existing Avro site

### PR DESCRIPTION
**Pull request by RyanSkraba**
Imports the existing [Avro website release docs](https://svn.apache.org/repos/asf/avro/site/publish/docs/) into this new website, Hopefully avoiding all broken links.

Everything that currently exists at https://avro.apache.org/docs/1.X.Y/ will be served as static content from this website.

After this change, https://avro-website.netlify.app/docs/1.10.1/ will point to the existing content, for example, but https://avro-website.netlify.app/docs/1.10.2/ will point to new content.

Maybe we should probably start delivering markdown content with new releases, and leave all existing releases like this?  What do you think?  I didn't succeed in getting `current` to work as a symlink to the most recent release yet.

### CODE REVIEW

**Comment by RyanSkraba** [comment]
Huh, it doesn't seem to work on the preview site.  I tested the change locally with docker:

```bash
cd avro
docker run --rm -v $(pwd):/src -p 1313:1313 jakejarvis/hugo-extended:latest server --buildDrafts --buildFuture --bind 0.0.0.0
```

I can take a closer look.

**Comment by martin-g** [comment]
> Huh, it doesn't seem to work on the preview site

I cannot review it - 5000+ changed files :-) Github UI gave up.
Did you run just `hugo` ? This will generate the HTMLs from the MDs.

**Comment by martin-g** [comment]
> Did you run just `hugo` ?

I should improve the README. It seems it does not mention it.

**Comment by RyanSkraba** [comment]
Haha -- it's overwhelming github!  This is more for discussion: how can we include all of the existing contents of the website without having to going back and rewriting docs for existing releases.

I don't think we should be putting in work to rewrite the <1.10.2 doc in markdown (even if it's much nicer), and it might even be worthwhile releasing 1.11.1 earlier just to have a new, clean website release.

> Did you run just hugo ? This will generate the HTMLs from the MDs.

When I run hugo via the docker command I showed on this branch, it builds the site including existing static content, and I can access http://localhost:1313/docs/1.9.2/

However, https://deploy-preview-4--avro-website.netlify.app/docs/1.9.2/ doesn't seem to work for me.

**Comment by martin-g** [comment]
Here is the work flow I recommend:
1) preview locally with `hugo server --navigateToChanged`
2) edit .md files
3) once satisfied with the changes, commit them: `git commit -a`
4) stop `hugo server --navigateToChanged` (Ctrl+C) and run `hugo`. This will generate the HTMLs in `public/` folder and this is what Netlify deployes
5) `git add . && git commit -a`
6) `git push`

This way even when the PR touches 5000+ files we can review only the first commit, the meaningful one, with the .md files

**Comment by martin-g** [comment]
I've updated the README with the work flow.

**Comment by martin-g** [comment]
I've just pulled your branch locally to see the changes:
```
git checkout -b RyanSkraba-rskraba/import-existing-site master
git pull https://github.com/RyanSkraba/avro-website.git rskraba/import-existing-site
```
and started Hugo:
```
hugo server --navigateToChanged
```

but I don't see the difference.
1.11.0 and 1.10.2 are local, but 1.10.1 and older versions still point to https://avro.apache.org/docs/x.y.z

**Comment by martin-g** [comment]
I've figured out the problem!
But I was not able to push to your repository with the improvements. So, I created https://github.com/martin-g/avro-website/pull/6 to be able to see the preview at Netlify.

**Comment by RyanSkraba** [comment]
Closed because this is obviously not a sustainable strategy!  I do think it's important to ensure we're not breaking old links though.

I'm also more-or-less against modifying spec documents that have already been published as "released", even if they aren't release artifacts, but I'll bring this up on the mailing list!

**Pull request closed without merging**
